#! /usr/bin/env bash
#
# pvers v0.7.1
# PHP Version Manager
#  
# Ivan Zinovyev <vanyazin@gmail.com>
#

function main {
    # Default values
    arg_help=false
    arg_list=false
    arg_delete=false
    arg_verbose=false
    arg_version=false
    arg_install=false
    arg_select=false

    # Parse input values
    parse_input $@

    # Routing
    # 
    if [[ $arg_help == true ]]; then
        c_help; exit 0

    elif [[ $arg_version == true ]]; then
        c_version; exit 0

    elif [[ $arg_list == true ]]; then
        c_list; exit 0

    elif [[ $arg_delete == true ]]; then
        is_root

        if [[ $arg_version == false ]]; then
            printf "You should provide a correct PHP version (5.0 and above).\n"\
            "Use '-h' or '--help' flag to get help.\n"

            exit 1
        fi

        c_delete $arg_version
        exit 0

    elif [[ $arg_install == true ]]; then
        is_root

        if [[ $arg_version == false ]]; then
            printf "You should provide a correct PHP version (5.0 and above).\n"\
            "Use '-h' or '--help' flag to get help.\n"

            exit 1
        fi

        c_install $arg_version
        exit 0

    elif [[ $arg_select == true ]]; then
        is_root

        if [[ $arg_version == false ]]; then
            printf "You should provide a correct PHP version (5.0 and above).\n"\
            "Use '-h' or '--help' flag to get help.\n"

            exit 1
        fi

        echo $arg_version; exit 1

        c_select $arg_version
        exit 0

    elif [[ $arg_version != false ]]; then
        is_root

        if [[ $arg_version == false ]]; then
            printf "You should provide a correct PHP version (5.0 and above).\n"\
            "Use '-h' or '--help' flag to get help.\n"

            exit 1
        fi

        # Init base pathes
        # @todo Configuration file
        basedir="/usr/share/pvers/"$version
        archive=$(echo "php-"$version".tar.bz2")
        srcdir=$(echo $basedir"/src")
        builddir=$(echo $basedir"/build")
        currdir="/usr/share/pvers/current"
        confpath="/etc/php"
        fpm_confpath=$builddir"/etc"

        c_install $arg_version
        c_select $arg_version
        exit 0

    else
        c_help; exit 0

    fi
}

# Command: print current version
function c_version {
    version="0.7.1"
    printf "pvers (PHP version manager) v"$version"\n"
}

# Print help info
function c_help {
    printf "\nUsage: %s\n"\
    "pvers [ options ... ] [php-version]"
    printf "Where options are:\n"
    printf "    %s\n"\
    "-h or --help        Print this message."\
    "-v or --version     Print pvers version."\
    "-l or --list        List locally installed PHP versions."\
    "-d or --delete      Remove locally installed PHP version (as root only)."\
    "-i or --delete      Install (only) PHP of given version (as root only)."\
    "-s or --delete      Select (only) PHP of given version (as root only)."\
    "-vv or --verbose    Verbose output (show all warnings and errors)."

    # -f or --force
    # -g or --global
    # -r or --recompile all    
    printf "To install or select (if already installed) PHP of version 5.6.6 type:\n\n%s\n\n"\
    "$ pvers 5.6.6"
}

# Command: list installed versions
function c_list {
    current=`ls -l /usr/share/pvers | awk '{if ($9=="current") {print $11}}' | awk -F/ '{print $5}'`
    ls -l /usr/share/pvers | awk -v cr=$current '{if (NR>1 && $9!="current" && $9!=cr) {print $9} else if ($9==cr) {print $9" [*]"}}'
}

# Command: build new PHP version
function c_install {
    version=$1

    # Check if another PHP version exists in a system
    if [[ ! -z `php -v 2>/dev/null` ]] && [[ ! -d /usr/share/pvers ]]; then
        echo "Another PHP interpreter is already installed in your system!"
        exit 1
    fi

    # Check if a wanted version is marked as an old release or not
    oldest_version="3" # For PHP-5.3
    wanted_version=$(echo $version | sed 's/5\.\([0-9]\{1,2\}\)\.[0-9]\{1,2\}/\1/')
    if [[ $wanted_version -le $oldest_version ]]; then

        while true; do
            read -p "You have selected an old version of PHP. It support is highly experimental. Really want to continue? [Y/n] " yn
            case $yn in
                [Yy]* ) break;;
                [Nn]* ) exit 0;;
                *) echo "Your answer should be directly Y or n!" ;;
            esac
        done

        url="http://museum.php.net/php5/"$archive
    else
        url="http://ru2.php.net/get/"$archive"/from/this/mirror"
    fi

    # Download && Compile
    if [ ! -d $basedir ]; then
        echo "Downloading..."
        mkdir -p `echo $basedir`
        cd $basedir;

        if [[ ! -d $basedir ]] || [[ $basedir != $(pwd) ]]; then
            echo "Can not create directory! Try running as su."
            exit 1
        fi

        wget -q $url

        echo "Extracting..."

        if [ -f mirror ]; then
            mv mirror $(echo $archive)
        elif [ ! -f $archive ]; then
            rm -rf $basedir
            echo "Failed to download! Try another version."; exit 1
        fi

        tar xjf $(echo $archive)
        mv $(echo "php-"$version) src
        rm $(echo $archive)                

        echo "Configuring..."
        cd src
        compile_options=("-q\
            --prefix="$builddir"\
            --with-config-file-path="$confpath"\
            --with-openssl\
            --enable-bcmath\
            --enable-fpm\
            --with-openssl\
            --with-curl\
            --enable-mbstring\
            --with-mysqli\
            --with-pdo-mysql\
            --with-libedit\
            --enable-soap\
            --enable-sockets")
        ./configure $compile_options >/dev/null 2>&1
        
        echo "Compiling..."
        if [[ `uname` == "Linux" ]]; then
            # Try using as much cores as possible
            make -s -i -k clean 1>/dev/null 2>&1 ; make -s -i -k -j $(grep -c ^processor /proc/cpuinfo) >/dev/null 2>&1 && make -s -i -k install >/dev/null 2>&1
        else
            make -s -i -k clean 1>/dev/null 2>&1 ; make -s -i -k -j >/dev/null 2>&1 && make -s -i -k install >/dev/null 2>&1
        fi

        # Applying php.ini
        echo "Applying php.ini..."
        if [[ ! -f /etc/php/php.ini && -f $(echo $srcdir"/php.ini-production") ]]; then
            mkdir -p /etc/php/
            cp -f $(echo $srcdir"/php.ini-production") /etc/php/php.ini
        fi

        # Create php-fpm.conf
        echo "Applying php-fpm.conf..."
        if [[ -d $fpm_confpath ]] && [[ -f $fpm_confpath"/php-fpm.conf.default" ]]; then
            cp $fpm_confpath"/php-fpm.conf.default" $fpm_confpath"/php-fpm.conf"
        fi

        echo "Successfully installed!"
    fi
}

# Command: select existing PHP version
function c_select {
    # Linking
    echo "Linking..."

    echo $1
    # version=$1
    success=true
    if [[ -d $basedir ]] && [[ -d $builddir ]]; then
        cd $basedir
    else
        echo "PHP of version "$version" is not installed or installation contains an error"
        exit 1
    fi

    if [[ -d $builddir"/bin" ]] || [[ -d $builddir"/sbin" ]]; then
        ln -sfT $builddir $currdir
        paths=("/bin/pear" "/bin/peardev" "/bin/pecl" "/bin/phar" "/bin/phar.phar" "/bin/php" "/bin/php-cgi" "/bin/php-config" "/bin/phpize" "/sbin/php-fpm")
        targdir="/usr"

        for path in ${paths[@]}; do
            if [[ -a $builddir$path ]]; then
                ln -sf $builddir$path $targdir$path
            else
                rm $targdir$path
            fi
        done
        echo "Current PHP version is "$version
    else
        echo "PHP of version "$version" is not installed or installation contains an error"
        exit 1
    fi
}

# Command: delete existing PHP version
function c_delete {
    if [ ! $1 ];  then
        echo "You must specify a PHP version you want to delete."
    elif [ ! -d "/usr/share/pvers/"$1 ] ; then
        echo "PHP version "$1" is not installed on your system."
    else
        while true; do
            read -p "Do you really want to delete php-"$1" from your computer? [Y/n] " yn
            case $yn in
                [Yy]* ) rm -rf "/usr/share/pvers/"$1; exit 0;;
                [Nn]* ) exit 0;;
                *) echo "Your answer should be directly Y or n!" ;;
            esac
        done
    fi
}

function parse_input {

    # Default values
    arg_help=false
    arg_list=false
    arg_delete=false
    arg_verbose=false
    arg_version=false
    arg_install=false
    arg_select=false

    # Walk through all args, mark selected options
    for arg in $@; do
        case $arg in
            "-h" | "--help" )
                arg_help=true
            ;;
            "-v" | "--version" )
                arg_version=true
            ;;
            "-l" | "--list" )
                arg_list=true
            ;;
            "-d" | "--delete" )
                arg_delete=true
            ;;
            "-i" | "--install" )
                arg_install=true
            ;;
            "-s" | "--select" )
                arg_select=true
            ;;
            "-vv" | "--verbose" )
                arg_verbose=true
            ;;
            * )
                if [ $(check_php_version $arg) == true ]; then
                    arg_version=$(fix_php_version $arg)
                    echo $arg_version; exit 1
                fi
            ;;
        esac
    done
}

# Check if user is root
function is_root {
    if [ $(id -u) != "0" ]; then
        printf "Run this script as root to use this option!\nUse '-h' or '--help' flag to get help.\n"
        exit 1
    fi
}

# Check if php version number is correct
function check_php_version {
    if [[ $1 =~ ^5\.[0-9]{1}\.{0,1}[0-9]{0,2}$ ]]; then
        echo true; return 1
    fi

    echo false; return 0
}

# Fix php version number
function fix_php_version {
    # Parse version number
    major=$(echo $1 | awk -F. '{print $2}')
    minor=$(echo $1 | awk -F. '{print $3}')

    # Fix minor version
    if [[ -z $minor ]]; then
        case $major in
            "0" ) minor=5;;
            "1" ) minor=6;;
            "2" ) minor=17;;
            "3" ) minor=29;;
            "4" ) minor=38;;
            "5" ) minor=22;;
            "6" ) minor=6;;
            "*" ) "Wrong major version (should be 0-6)!"; exit 1 ;;
        esac
        echo "5."$major"."$minor
    else
        echo $1
    fi
}

# @todo Select a mirror
function get_mirrors {
    echo 'todo'
}

main $@